.gitignore, app.js, config/config.js, controller/Cboard.js, controller/Ccomment.js, controller/Cmeet.js, controller/Ctodo.js, controller/Cuser.js, models/DoneTodo.js, models/Meet.js, models/MeetBoard.js, models/MeetBoardComment.js, models/MeetBoardCommentReply.js, models/MeetBoardIcon.js, models/MeetUser.js, models/TotalTodo.js, models/User.js, models/index.js, package.json, routes/board.js, routes/comment.js, routes/meet.js, routes/todo.js, routes/user.js
1. mvc 패턴으로 코드 작성
2. 대부분 파일만 생성 (안의 코드는 dummy 코드 작성)
3. 개발용과 배포용을 따로 구분해서 설정파일 작성(config.js) 후 package.json에 작성
- 개발용 : $ npm start
- 배포용 : $ npm run start:prod
=> feat ::: 백엔드 초기 프로젝트 파일 생성 (일부 파일은 dummy 코드 작성)

controller/Cuser.js, routes/user.js
=> 구글 로그인 진행 중

controller/Cuser.js
=> fix: 네이버 로그인 경로 수정

app.js, config/config.js, package.json, routes/index.js, routes/user.js, utils/swagger/swagger.js
1. swagger 적용 완료
※ 주의사항 : swagger 주석처럼 되어있는 부분은 무조건 그대로 쓰셔야합니다.
swagger 주석이랑 코드 복붙해서 내용만 수정해주세요.
+ tags가 일치해야 합니다.
2. router 분리
이제는 app.js → indexRouter → 기능Router로 이동합니다.
3. utils 폴더를 생성했습니다.
자주 쓰일 것 같은 함수/클래스 등을 작성하시는 경우에는 utils 폴더 안에 파일 생성하셔서 만드시면 됩니다.
=> feat ::: swagger 적용 완료

routes/group.js, routes/index.js, routes/user.js
태그명 규칙 적용
1. 대문자 / 설명은 ~~ 관련 API
Ex. User / 유저 관련 API
=> fix ::: swagger tags 수정

config/secretkey.js, controller/Cgroup.js, package.json, routes/group.js, routes/user.js
=> feat ::: 모임 생성 임시 완료

modules/swagger/component/GroupComponent.yaml, modules/swagger/parameter/GroupParameter.yaml, modules/swagger/requestBody/GroupRequestBody.yaml, modules/swagger/response/GroupResponse.yaml, modules/swagger/swagger.js, package.json, routes/group.js, routes/index.js
1. modules/swagger 폴더를 세부적으로 작성
- component : schema 정의
- parameter : 파라미터 정의 (req.query 혹은 req.params 인 듯)
- requestBody : requestBody 정의
- response : response 정의
component 제외 모두 의미 없는 코드임
=> fix ::: swagger yaml파일 분리 적용 완료 / 일부는 의미 없는 코드

app.js, config/config.js
=> fix ::: MySQL 타임존 수정

controller/Cmission.js, modules/swagger/response/missionResponse.yaml
=> docs/mission : swagger문서 수정

controller/Cmission.js
=> fix/mission: mission load 에러 수정

controller/Cuser.js
jwtToken.token 값, alreadyUser 로직에
naver만 await가 빠져있었네요
=> fix/naverLogin: 토큰값 확인

config/config.js, controller/Cuser.js
로컬 및 서버배포시 네이버 시크릿 아이디/패스워드 분리
=> fix/naverLogin : 로컬/배포 분리

controller/Cgroup.js, modules/rankSystem.js
=> feat/group : 그룹 미션 총 점수 합산 추가

controller/Cgroup.js, controller/Cmission.js, modules/rankSystem.js, modules/swagger/parameter/GroupParameter.yaml, modules/swagger/requestBody/MissionRequestBody.yaml, modules/swagger/requestBody/UserRequestBody.yaml, modules/swagger/response/GroupResponse.yaml, modules/swagger/response/missionResponse.yaml, routes/group.js, routes/mission.js
1. 유저 미션 리스트 
2. 그룹 미션 리스트
3. 미션 수정(디데이, 미션내용, 미션 제목, 난이도)
=> feat/mission : 미션 수정, 미션리스트(유저/그룹)

controller/Cgroup.js, controller/Cuser.js, modules/rankSystem.js, modules/swagger/response/GroupResponse.yaml
랭킹 시스템 구현 완료
1. 유저의 모임별 달성률
2. 모임 내 유저별 달성률
3. 모임 현재 랭킹순위
4. 모임 누적 랭킹순위
5. 모임 현재 달성률 순위
=> feat/doneRates: 유저 달성률, 모임내 유저별 달성률, 현재랭킹, 누적랭킹

app.js, controller/Cgroup.js
=> fix ::: 모임 생성 수정

routes/group.js
=> 그룹채팅 부활 (임시)

app.js, models/GroupBoardComment.js, models/index.js
=> fix ::: 댓글 수정

app.js
=>  fix ::: Swagger 로그인 설정 해제 (포트폴리오를 위함)

controller/Cboard.js, controller/Cmission.js, modules/rankSystem.js
=> fix/userMission : 미션달성후 안보이는 에러 수정

controller/Cboard.js, modules/rankSystem.js
본인 미션글 삭제시 점수하락 반영
(복수개 작성된 경우에는 점수하락되지 않음)
=> feat/downScore: 게시글삭제시 점수하락

README.md, app.js, controller/Cgroup.js, public/chat.html
=> docs ::: 리드미 ERD 이미지 수정

controller/Cgroup.js, controller/Cmission.js, modules/rankSystem.js
모임 patch : gDday 추가
미션 patch : gDday 삭제
=> fix/missionEdit: 미션 수정시 점수 에러 수정
